### ISSUE TITLE
Stop using Ubuntu 18.04

### ISSUE THREAD

**Issue by Adjective-Object** [Adjective-Object/good-fences-rs-core#23]
Ubuntu 18.04 is EOL next April.
https://computing.cs.cmu.edu/news/2022/eol-ubuntu-1804

This is a footgun waiting to happen, the pipeline will start to spontaneously fail on April 4th of next year.

https://github.com/actions/runner-images/issues/6002

We can instead try to statically link against musl instead of dynamically linking glibc. Someone else had already documented the approach: ttps://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

Filing this so it doesn't get forgotten, I'm fine to concentrate on shipping for now. But this needs to get fixed before early next year.

**Comment by Adjective-Object** [comment]
Related to #19

**Comment by flickyiyo** [comment]
After looking for some way to fix this found this https://github.com/awslabs/aws-lambda-rust-runtime/discussions/306

After testing on my local seems that using `linux-musl` instead of `gnu` as target works fine for ubuntu 18 and newer, all compiled from `ubuntu-latest`

**Comment by flickyiyo** [comment]
Fixed in #50
